services:
  flatcar_mirror:
    build: 
      context: ./src/flatcar
      dockerfile: flatcar_mirror.Dockerfile
    volumes:
      - ./mnt/flatcar:/data/
    command: [ "--channels", "stable,beta,alpha","--above-version","2700"]
  flatcar_fileserver_stable:
      image: halverneus/static-file-server
      environment: 
        - PORT=8080
        - FOLDER=/var/www/
      volumes:
        - ./mnt/flatcar/stable:/var/www/
      ports: 
        - 8280:8080
  flatcar_fileserver_beta:
    image: halverneus/static-file-server
    environment: 
      - PORT=8080
      - FOLDER=/var/www/
    volumes:
      - ./mnt/flatcar/beta:/var/www/
    ports: 
      - 8081:8080
  flatcar_fileserver_alpha:
    image: halverneus/static-file-server
    environment: 
      - PORT=8080
      - FOLDER=/var/www/
    volumes:
      - ./mnt/flatcar/alpha:/var/www/
    ports: 
      - 8082:8080